"""remove prof level in skills table

Revision ID: 804e94079d27
Revises: ff6138599843
Create Date: 2025-11-09 11:57:43.729252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804e94079d27'
down_revision: Union[str, Sequence[str], None] = 'ff6138599843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'proficiency_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('proficiency_level', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
