"""Add logo url to skills and companies

Revision ID: ea3fb2d04124
Revises: None
Create Date: 2025-11-23 17:32:55.858487

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = 'ea3fb2d04124'
down_revision: str | Sequence[str] | None = '0000000000'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    insp = inspect(conn)

    companies_cols = {c['name'] for c in insp.get_columns('companies')}
    skills_cols = {c['name'] for c in insp.get_columns('skills')}

    if 'logo_url' not in companies_cols:
        op.add_column('companies', sa.Column('logo_url', sa.String(length=500), nullable=True))
    if 'logo_url' not in skills_cols:
        op.add_column('skills', sa.Column('logo_url', sa.String(length=500), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'logo_url')
    op.drop_column('companies', 'logo_url')
    # ### end Alembic commands ###
