"""remove location in company

Revision ID: ff6138599843
Revises: cf762c0cb2b6
Create Date: 2025-11-09 11:54:13.597008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6138599843'
down_revision: Union[str, Sequence[str], None] = 'cf762c0cb2b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'headquarters')
    op.drop_column('companies', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('headquarters', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
